### ISSUE TITLE
XMPP or IRC support?

### ISSUE THREAD

**Issue by poVoq** [silkeh/mumble_bot#1]
Both would be pretty nice additions.

Thanks for considering :)

**Comment by silkeh** [comment]
At this moment the project only supports sending stickers to Matrix or Telegram. Because (I believe) XMPP and IRC don't have any native sticker functionality, it would not be possible to support those protocols.

A possible solution is to use a Matrix bridge, so media would be translated somewhat correctly. 

Feel free to add a comment when there is native support for stickers in XMPP or Matrix, and I will reopen this.
